
# Site settings
title: Jiachen Zhang
name: Jiachen Zhang
subtitle: Ph.D. Candidate in MIE UofT
email: jasonzhangjc.zhang@mail.utoronto.ca
description: >
  Ph.D. Candidate in MIE UofT
baseurl: ""
url: "https://jasonzhangjc.github.io/"
github_username:  JasonZhangjc
disqus_baseurl: "https://jasonzhangjc.github.io/"
disqus_shortname: https-jasonzhangjc-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Jiachen Zhang"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: JasonZhangjc
    url: https://github.com/JasonZhangjc
    desc: Fork me on GitHub
    share: false
